apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - port: 80
      name: http
      targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
          command:
            - sh
            - -c
            - until pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT; do sleep 1; done
        - name: wait-for-rabbit
          image: murzayev/otu_stream_processing_rabbit_isready:latest
          env:
            - name: RABBIT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_PASSWORD
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RABBIT_HOST
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RABBIT_PORT
          command:
            - sh
            - -c
            - until /app/app.bin; do sleep 1; done
      containers:
        - name: notification
          image: murzayev/otu_stream_processing_notification:latest
          ports:
            - name: http
              containerPort: 7775
          env:
            - name: PORT
              value: "7775"
            - name: RABBIT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_PASSWORD
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RABBIT_HOST
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RABBIT_PORT
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: QUEUE_NAME
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_SSLMODE
          livenessProbe:
            httpGet:
              port: 7775
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 7775
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 2